fptools/libraries/HaXml: changeset 2003-05-30 15:46:44 by malcolm
Fix version detection for ghc >= 6.0. Add rudimentary detection for
Hugs, but it doesn't work yet.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -50,9 +50,11 @@ echo "Looking for Haskell compilers:"
 HMAKEKNOWN=
 GHCKNOWN=
 NHCKNOWN=
+HUGSKNOWN=
 HMAKENUM=0
 GHCNUM=0
 NHCNUM=0
+HUGSNUM=0
 
 echo -n "  Looking for hmake... "
 if which hmake >/dev/null 2>&1
@@ -72,6 +74,9 @@ then
   GHCKNOWN=`which ghc`
   GHCVERSION=`${GHCKNOWN} --version 2>&1 | sed 's/^.*version[ ]*\([0-9.]*\).*/\1/'`
   GHCNUM=`echo $GHCVERSION | tr "v." " " | ( read x y z; echo $x$y; )`
+  if [ "$GHCNUM" -lt "100" ]
+  then GHCNUM=${GHCNUM}0
+  fi
 fi
 if [ "$GHCKNOWN" = "" ]
 then echo "(not found)"
@@ -98,6 +103,9 @@ then
       GHC2KNOWN=`which $BUILDWITH`
       GHC2VERSION=`${GHC2KNOWN} --version 2>&1 | sed 's/^.*version[ ]*\([0-9.]*\).*/\1/'`
       GHC2NUM=`echo $GHC2VERSION | tr "." " " | ( read x y z; echo $x$y; )`
+      if [ "$GHC2NUM" -lt "100" ]
+      then GHC2NUM=${GHC2NUM}0
+      fi
     fi
     if [ "$GHC2KNOWN" = "" ]
     then  echo "(not found)"
@@ -139,6 +147,24 @@ else  echo "found ${NHCVERSION}"
      fi
 fi
 
+echo -n "  Looking for hugs...  "
+if which hugs >/dev/null 2>&1
+then
+  HUGSKNOWN=`which hugs`
+  HUGSVERSION="(unknown version)"
+  HUGSNUM=000
+fi
+if [ "$HUGSKNOWN" = "" ]
+then  echo "(not found)"
+else  echo "found ${HUGSVERSION}"
+  if [ "$HUGSNUM" -lt "20030101" ]
+  then  echo "    Warning: HaXml configuration does not yet support Hugs."
+        HUGSKNOWN=
+  else  HUGSLIBDIR="..."
+        HUGSINCDIR="..."
+    fi
+fi
+
 if [ ! -z "$BUILDWITH" ]
 then
   echo "  You want to build for only...  $BUILDWITH"
@@ -148,17 +174,27 @@ then
     then echo '   *** Did not find ghc - cannot continue.'
          exit 1
     else NHCKNOWN=
+         HUGSKNOWN=
     fi
-  else
-    if [ "$BUILDWITH" = "nhc98" ]
-    then
-      if [ -z "$NHCKNOWN" ]
-      then echo '   *** Did not find nhc98 - cannot continue.'
-           exit 1
-      else GHCKNOWN=
-      fi
+  else if [ "$BUILDWITH" = "nhc98" ]
+  then
+    if [ -z "$NHCKNOWN" ]
+    then echo '   *** Did not find nhc98 - cannot continue.'
+         exit 1
+    else GHCKNOWN=
+         HUGSKNOWN=
     fi
-  fi
+  else if [ "`echo $BUILDWITH | cut -c1-4`" = "hugs" ]
+  then
+    if [ -z "$HUGSKNOWN" ]
+    then echo '   *** Did not find hugs - cannot continue.'
+         exit 1
+    else GHCKNOWN=
+         NHCKNOWN=
+    fi
+  else echo '   *** I do not recognise this compiler:' $BUILDWITH
+       exit 1
+  fi;fi;fi;
 fi
 
 echo "  Executables install into... $INSTALLDIR"
@@ -197,9 +233,22 @@ then
   echo $NHCLIBDIR >obj/nhc98/nhc98libdir
   echo $NHCINCDIR >obj/nhc98/nhc98incdir
   cp -Rp src/Text src/tools src/Makefile obj/nhc98
+  if [ "$NHCNUM" -ge "116" ]
+  then rm -rf obj/ghc/Text/PrettyPrint
+       echo "-package base" >obj/nhc98/nhc98pkgs
+  else echo "" >obj/nhc98/nhc98pkgs
+  fi
 fi
+if [ "$HUGSKNOWN" != "" ]
+then
+  #cp -Rp src/Text src/tools src/Makefile obj/hugs
+  hugs-package src
+  echo 'I have installed the HaXml package for Hugs.'
+fi
+
 echo $INSTALLDIR >obj/prefix
 if $CYGWIN; then echo .exe >obj/exe; else touch obj/exe; fi
+
 
 echo "Ready to build.  Type 'make' then (as root) 'make install'."
 exit 0
